INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (1, '10739', 'ACXM Automotive > Car Rental > Business Use', 'This element ranks the likelihood that someone in this household has used a car rental for business use in the last 12 months.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (2, '300441499', 'ACXM Automotive > Likely In Market Timing > New Luxury Vehicle', 'This element ranks the likelihood that the household may have Affinity for a Luxury Vehicle.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (3, '300448599', 'ACXM Automotive > Likely In Market Timing > New Vehicle', 'This element ranks the likelihood that the household may be In Market for a New Vehicle.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (4, '300614099', 'ACXM Automotive > Likely In Market Timing > Used Vehicle', 'This element ranks the likelihood that the household may be In Market for a Used Vehicle.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (5, '300449599', 'ACXM Automotive > Likely New Vehicle Brand > Acura', 'This element ranks the likelihood that the household may have Affinity for a New Acura.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (6, '300449699', 'ACXM Automotive > Likely New Vehicle Brand > Audi', 'This element ranks the likelihood that the household may have Affinity for a New Audi.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (7, '300449799', 'ACXM Automotive > Likely New Vehicle Brand > BMW', 'This element ranks the likelihood that the household may have Affinity for a New BMW.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (8, '300449899', 'ACXM Automotive > Likely New Vehicle Brand > Buick', 'This element ranks the likelihood that the household may have Affinity for a New Buick.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (9, '300449999', 'ACXM Automotive > Likely New Vehicle Brand > Cadillac', 'This element ranks the likelihood that the household may have Affinity for a New Cadillac.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (10, '300450299', 'ACXM Automotive > Likely New Vehicle Brand > Chevrolet', 'This element ranks the likelihood that the household may have Affinity for a New Chevrolet.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (11, '300450099', 'ACXM Automotive > Likely New Vehicle Brand > Chevrolet Car', 'This element ranks the likelihood that the household may have Affinity for a New Chevrolet Car.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (12, '300450199', 'ACXM Automotive > Likely New Vehicle Brand > Chevrolet Truck', null);
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (13, '300450399', 'ACXM Automotive > Likely New Vehicle Brand > Chrysler', 'This element ranks the likelihood that the household may have Affinity for a New Chrysler.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (14, '300450499', 'ACXM Automotive > Likely New Vehicle Brand > Dodge', 'This element ranks the likelihood that the household may have Affinity for a New Dodge.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (15, '300450799', 'ACXM Automotive > Likely New Vehicle Brand > Ford', 'This element ranks the likelihood that the household may have Affinity for a New Ford.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (16, '300450599', 'ACXM Automotive > Likely New Vehicle Brand > Ford Car', 'This element ranks the likelihood that the household may have Affinity for a New Ford Car.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (17, '300450699', 'ACXM Automotive > Likely New Vehicle Brand > Ford Truck', 'This element ranks the likelihood that the household may have Affinity for a New Ford Truck.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (18, '300450899', 'ACXM Automotive > Likely New Vehicle Brand > GMC', 'This element ranks the likelihood that the household may have Affinity for a New GMC.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (19, '300450999', 'ACXM Automotive > Likely New Vehicle Brand > Honda', 'This element ranks the likelihood that the household may have Affinity for a New Honda.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (20, '300451099', 'ACXM Automotive > Likely New Vehicle Brand > Hyundai', 'This element ranks the likelihood that the household may have Affinity for a New Hyundai.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (21, '300451199', 'ACXM Automotive > Likely New Vehicle Brand > Infiniti', 'This element ranks the likelihood that the household may have Affinity for a New Infiniti.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (22, '300451299', 'ACXM Automotive > Likely New Vehicle Brand > Jaguar', 'This element ranks the likelihood that the household may have Affinity for a New Jaguar.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (23, '300451399', 'ACXM Automotive > Likely New Vehicle Brand > Jeep', 'This element ranks the likelihood that the household may have Affinity for a New Jeep.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (24, '300451499', 'ACXM Automotive > Likely New Vehicle Brand > Kia', 'This element ranks the likelihood that the household may have Affinity for a New Kia.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (25, '300451599', 'ACXM Automotive > Likely New Vehicle Brand > Land Rover', 'This element ranks the likelihood that the household may have Affinity for a New Land Rover.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (26, '300451699', 'ACXM Automotive > Likely New Vehicle Brand > Lexus', 'This element ranks the likelihood that the household may have Affinity for a New Lexus.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (27, '300451799', 'ACXM Automotive > Likely New Vehicle Brand > Lincoln', 'This element ranks the likelihood that the household may have Affinity for a New Lincoln.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (28, '300451899', 'ACXM Automotive > Likely New Vehicle Brand > Mazda', 'This element ranks the likelihood that the household may have Affinity for a New Mazda.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (29, '300451999', 'ACXM Automotive > Likely New Vehicle Brand > Mercedes Benz', 'This element ranks the likelihood that the household may have Affinity for a New Mercedes Benz.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (30, '300452099', 'ACXM Automotive > Likely New Vehicle Brand > Mini', 'This element ranks the likelihood that the household may have Affinity for a New Mini.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (31, '300452199', 'ACXM Automotive > Likely New Vehicle Brand > Mitsubishi', 'This element ranks the likelihood that the household may have Affinity for a New Mitsubishi.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (32, '300452299', 'ACXM Automotive > Likely New Vehicle Brand > Nissan', 'This element ranks the likelihood that the household may have Affinity for a New Nissan.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (33, '300025699', 'ACXM Automotive > Likely New Vehicle Brand > Own or Lease Any Honda Vehicle', 'Households with people who are likely to own or lease a Honda vehicle');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (34, '300452399', 'ACXM Automotive > Likely New Vehicle Brand > Porsche', 'This element ranks the likelihood that the household may have Affinity for a New Porsche.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (35, '300454999', 'ACXM Automotive > Likely New Vehicle Brand > Ram', 'This element ranks the likelihood that the household may have Affinity for a New Ram.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (36, '300452499', 'ACXM Automotive > Likely New Vehicle Brand > Scion', 'This element ranks the likelihood that the household may have Affinity for a New Scion.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (37, '300452599', 'ACXM Automotive > Likely New Vehicle Brand > Suburu', 'This element ranks the likelihood that the household may have Affinity for a New Subaru.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (38, '300002799', 'ACXM Automotive > Likely New Vehicle Brand > Suzuki', 'Households with people who are likely to have a vehicle brand preference for New Suzuki');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (39, '300452899', 'ACXM Automotive > Likely New Vehicle Brand > Toyota', 'This element ranks the likelihood that the household may have Affinity for a New Toyota.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (40, '300452699', 'ACXM Automotive > Likely New Vehicle Brand > Toyota Car', 'This element ranks the likelihood that the household may have Affinity for a New Toyota Car.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (41, '300452799', 'ACXM Automotive > Likely New Vehicle Brand > Toyota Truck', 'This element ranks the likelihood that the household may have Affinity for a New Toyota Truck.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (42, '300452999', 'ACXM Automotive > Likely New Vehicle Brand > Volkswagen', 'This element ranks the likelihood that the household may have Affinity for a New Volkswagen.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (43, '300453099', 'ACXM Automotive > Likely New Vehicle Brand > Volvo', 'This element ranks the likelihood that the household may have Affinity for a New Volvo.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (44, '300448799', 'ACXM Automotive > Likely New Vehicle Payment Preference > Finance', 'This element ranks the likelihood that the household may Finance a New Vehicle.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (45, '300448899', 'ACXM Automotive > Likely New Vehicle Payment Preference > Lease', 'This element ranks the likelihood that the household may Lease a New Vehicle.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (46, '300448699', 'ACXM Automotive > Likely New Vehicle Payment Preference > Pay Cash', 'This element ranks the likelihood that the household may Pay Cash for a New Vehicle.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (47, '300456299', 'ACXM Automotive > Likely New Vehicle Type > Electric', 'This element ranks the likelihood that the household may Purchase a New Electrical Car.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (48, '300456399', 'ACXM Automotive > Likely New Vehicle Type > Hybrid', 'This element ranks the likelihood that the household may Purchase a New Hybrid Car.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (49, '10748', 'ACXM Automotive > Vehicle Type > Compact Car', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (50, '10749', 'ACXM Automotive > Vehicle Type > Luxury Car', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (51, '10750', 'ACXM Automotive > Vehicle Type > Mid or Full Size Car', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (52, '10751', 'ACXM Automotive > Vehicle Type > Motorcycle', 'Someone in the household has indicated that they own a truck, motorcycle or RV. This does not include SUV''s. It is important to note that most vehicles that are considered by the public to be SUV''s are really trucks. (i.e. Long wheel based Chevy Suburban is considered a truck. Acxiom’s vehicle data does not fall under the DPPA (Driver’s Privacy Protection Act). The DPPA prohibits the release or use of personal information about an individual in connection with a motor vehicle record. Acxiom’s vehicle data is not sourced from motor vehicle records. It is sourced from surveys, completed by consumers, which were sent due to a vehicle warranty purchase, vehicle service/repair or from a product registration.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (53, '10752', 'ACXM Automotive > Vehicle Type > Recreational Vehicle', 'Someone in the household has indicated that they own a truck, motorcycle or RV. This does not include SUV''s. It is important to note that most vehicles that are considered by the public to be SUV''s are really trucks. (i.e. Long wheel based Chevy Suburban is considered a truck) Acxiom’s vehicle data does not fall under the DPPA (Driver’s Privacy Protection Act). The DPPA prohibits the release or use of personal information about an individual in connection with a motor vehicle record. Acxiom’s vehicle data is not sourced from motor vehicle records. It is sourced from surveys, completed by consumers, which were sent due to a vehicle warranty purchase, vehicle service/repair or from a product registration.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (54, '10753', 'ACXM Automotive > Vehicle Type > Sport/Utility Vehicle', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (55, '10754', 'ACXM Automotive > Vehicle Type > Sports Car', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (56, '10755', 'ACXM Automotive > Vehicle Type > Truck', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (57, '10756', 'ACXM Automotive > Vehicle Type > Van', 'This element indicates the type of vehicle that exists in Vehicle 1 (elements 9040-9044). It can be used to determine the household''s vehicle ''lifestyle''.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (58, '10576', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Animal Welfare', 'People who donate money to animal welfare.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (59, '10578', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Charitable Causes', 'People who donate money to any charitable cause.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (60, '10579', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Children''s Interests', 'People who donate money to children''s causes.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (61, '10580', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Environment or Wildlife Causes', 'People who donate money to environmental or wildlife causes.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (62, '10581', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Health Causes', 'People who donate money to health causes.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (63, '10584', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Political', 'People who donate money to political causes.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (64, '10587', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Religious Causes', 'People who donate money to religious causes.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (65, '10588', 'ACXM Charities and Causes > Community Involvement - Causes Supported Financially > Veteran''s Causes', 'People who donate money to veterans causes.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (66, '4131', 'ACXM Demographic > Age > 1st Individual > 18-24', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included. An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (67, '4132', 'ACXM Demographic > Age > 1st Individual > 25 - 29', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (68, '4133', 'ACXM Demographic > Age > 1st Individual > 30 - 34', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (69, '4134', 'ACXM Demographic > Age > 1st Individual > 35 - 39', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (70, '4135', 'ACXM Demographic > Age > 1st Individual > 40 - 44', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (71, '4136', 'ACXM Demographic > Age > 1st Individual > 45 - 49', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (72, '4137', 'ACXM Demographic > Age > 1st Individual > 50 - 54', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (73, '4138', 'ACXM Demographic > Age > 1st Individual > 55 - 59', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (74, '4139', 'ACXM Demographic > Age > 1st Individual > 60 - 64', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (75, '4140', 'ACXM Demographic > Age > 1st Individual > 65+', 'Indicates the Year and Month of Birth associated with the individual''s name appearing on the customer''s 1st file. The DAY of birth is not included.
An estimated 3% of matched records will only contain year of birth data.
* This DOB element contains no DAY of birth, but the length of the element is 8 positions (YYYYMM00). Whenever there is a Year and a Month present in this element, the day portion of the element will be set to 00.
* The valid values for the month portion of the field are 01-12. When the year is present, but the month is unknown, the month portion will be defaulted to 00.
* When there is no year of birth and no month of birth present, the entire element field is set to blanks.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (76, '1823', 'ACXM Demographic > Age > Five-Year Range > 18-24', 'Households with people including someone aged 18-24');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (77, '1824', 'ACXM Demographic > Age > Five-Year Range > 25-29', 'Households with people including someone aged 25-29');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (78, '1825', 'ACXM Demographic > Age > Five-Year Range > 30-34', 'Households with people including someone aged 30-34');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (79, '1826', 'ACXM Demographic > Age > Five-Year Range > 35-39', 'Households with people including someone aged 35-39');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (80, '1827', 'ACXM Demographic > Age > Five-Year Range > 40-44', 'Households with people including someone aged 40-44');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (81, '1828', 'ACXM Demographic > Age > Five-Year Range > 45-49', 'Households with people including someone aged 45-49');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (82, '1829', 'ACXM Demographic > Age > Five-Year Range > 50-54', 'Households with people including someone aged 50-54');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (83, '10784', 'ACXM Demographic > Age > Five-Year Range > 55 - 59', 'Households with people including someone aged 55-59');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (84, '10785', 'ACXM Demographic > Age > Five-Year Range > 60 - 64', 'Households with people including someone aged 60-64');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (85, '10786', 'ACXM Demographic > Age > Five-Year Range > 65+', 'Households with people including someone aged 65+');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (86, '10428', 'ACXM Demographic > Children Age > 00-02', 'Households with people who have children that are aged between 0 - 2 (all genders combined).');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (87, '10429', 'ACXM Demographic > Children Age > 03-05', 'Households with people who have children that are aged between 16 - 17 (all genders combined).');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (88, '10430', 'ACXM Demographic > Children Age > 06-10', 'Households with people who have children that are aged between 3 - 5 (all genders combined).');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (89, '10431', 'ACXM Demographic > Children Age > 11-15', 'Households with people who have children that are aged between 6 - 10 (all genders combined).');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (90, '10432', 'ACXM Demographic > Children Age > 16-17', 'Households with people who have children that are aged between 11 - 15 (all genders combined).');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (91, '4143', 'ACXM Demographic > Education > 1st Individual > College', 'Indicates the highest known education of the 1st individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (92, '4144', 'ACXM Demographic > Education > 1st Individual > Graduate School', 'Indicates the highest known education of the 1st individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (93, '4142', 'ACXM Demographic > Education > 1st Individual > High School', 'Indicates the highest known education of the 1st individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (94, '10796', 'ACXM Demographic > Education > Input Individual > Attended Vocational/Technical', 'Indicates the highest known education of the input individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (95, '10794', 'ACXM Demographic > Education > Input Individual > College', 'Indicates the highest known education of the input individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (96, '10795', 'ACXM Demographic > Education > Input Individual > Graduate School', 'Indicates the highest known education of the input individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (97, '10793', 'ACXM Demographic > Education > Input Individual > High School', 'Indicates the highest known education of the input individual''s name appearing on the customer''s input file.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (98, '1200', 'ACXM Demographic > Ethnicity > African American', 'Households with people who are are African American.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (99, '1199', 'ACXM Demographic > Ethnicity > Asian', 'Households with people who are are Asian.');
INSERT INTO user_data_directory (id, segment_id, segment_name, description) VALUES (100, '10500', 'ACXM Demographic > Ethnicity > Hispanic', 'Households with people who are Hispanic');
